AllCops:
  Include:
    - Berksfile
    - Gemfile
    - Rakefile
    - Thorfile
    - Guardfile
    - Vagrantfile
    - chef_aws_provisioner.gemspec
  Exclude:
    - vendor/**
    - .kitchen/**
ClassLength:
  Enabled: false
Documentation:
  Enabled: false
Encoding:
  Enabled: false
HashSyntax:
  Enabled: false
LineLength:
  Enabled: false
MethodLength:
  Enabled: false
SignalException:
  Enabled: false
Style/FileName:
  Enabled: false
